"""Add name to Device and color to DataStream

Revision ID: 4513b74b2b3c
Revises: 
Create Date: 2026-03-15 20:14:45.231446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4513b74b2b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_stream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('data_stream', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
