"""add datapoint and hourly aggregate composite indexes

Revision ID: a04dd7ccab2e
Revises: 4513b74b2b3c
Create Date: 2026-03-22 10:06:52.592401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04dd7ccab2e'
down_revision = '4513b74b2b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.create_index('idx_datapoint_device_pin_ts', ['device_mac', 'pin', 'timestamp'], unique=False)

    with op.batch_alter_table('hourly_aggregate', schema=None) as batch_op:
        batch_op.create_index('idx_hourly_device_pin_bucket', ['device_mac', 'pin', 'hour_bucket'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hourly_aggregate', schema=None) as batch_op:
        batch_op.drop_index('idx_hourly_device_pin_bucket')

    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_index('idx_datapoint_device_pin_ts')

    # ### end Alembic commands ###
