"""add device command lifecycle table

Revision ID: d3cd6889471b
Revises: a04dd7ccab2e
Create Date: 2026-03-22 10:13:27.821583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cd6889471b'
down_revision = 'a04dd7ccab2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(length=36), nullable=False),
    sa.Column('device_mac', sa.String(length=20), nullable=False),
    sa.Column('command_type', sa.String(length=20), nullable=False),
    sa.Column('pin', sa.String(length=20), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('ack_event', sa.String(length=40), nullable=True),
    sa.Column('ack_message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('ack_at', sa.DateTime(), nullable=True),
    sa.Column('timeout_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_mac'], ['device.mac'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_command', schema=None) as batch_op:
        batch_op.create_index('idx_command_device_status_created', ['device_mac', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_command_command_id'), ['command_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_command_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_command_device_mac'), ['device_mac'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_command_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_command_status'))
        batch_op.drop_index(batch_op.f('ix_device_command_device_mac'))
        batch_op.drop_index(batch_op.f('ix_device_command_created_at'))
        batch_op.drop_index(batch_op.f('ix_device_command_command_id'))
        batch_op.drop_index('idx_command_device_status_created')

    op.drop_table('device_command')
    # ### end Alembic commands ###
